# Generated by Django 6.0.6 on 2026-07-01 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del curso')),
                ('instructor', models.CharField(max_length=100, verbose_name='Instructor')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración (horas)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=15, verbose_name='Modalidad')),
                ('cupos', models.PositiveIntegerField(verbose_name='Cupos disponibles')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota final')),
                ('estado', models.CharField(choices=[('Inscrito', 'Inscrito'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Retirado', 'Retirado')], default='Inscrito', max_length=15, verbose_name='Estado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='tecnicos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código de certificado')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Archivo PDF')),
                ('participacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='tecnicos.participacion', verbose_name='Participación')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('especialidad', models.CharField(choices=[('Desarrollo Web', 'Desarrollo Web'), ('Redes y Telecomunicaciones', 'Redes y Telecomunicaciones'), ('Ciberseguridad', 'Ciberseguridad'), ('Soporte Técnico', 'Soporte Técnico'), ('Base de Datos', 'Base de Datos'), ('Inteligencia Artificial', 'Inteligencia Artificial'), ('Cloud Computing', 'Cloud Computing'), ('Desarrollo Móvil', 'Desarrollo Móvil')], max_length=50, verbose_name='Especialidad')),
                ('institucion', models.CharField(max_length=150, verbose_name='Institución')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tecnicos/', verbose_name='Foto')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='participacion',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='tecnicos.tecnico', verbose_name='Técnico'),
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('tecnico', 'curso')},
        ),
    ]
