# Generated by Django 6.0.6 on 2026-07-16 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cupos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Cupos disponibles'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota final'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$', 'Los apellidos solo pueden contener letras y espacios.')], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe tener exactamente 10 dígitos numéricos.')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$', 'Los nombres solo pueden contener letras y espacios.')], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener exactamente 10 dígitos numéricos.')], verbose_name='Teléfono'),
        ),
    ]
